"""create patients table

Revision ID: 90cfb5542e04
Revises: 73004098e17e
Create Date: 2024-02-09 20:49:35.920695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '90cfb5542e04'
down_revision: Union[str, None] = '73004098e17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic -
    pass


def downgrade() -> None:
    pass
    # ### end Alembic commands ###
