// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9S7RCLLDgcBx_9SWhQAY_wSjiMdhMMTc',
    appId: '1:525146998604:web:34da26156b0b3a53de71e9',
    messagingSenderId: '525146998604',
    projectId: 'a-eye-397619',
    authDomain: 'a-eye-397619.firebaseapp.com',
    storageBucket: 'a-eye-397619.appspot.com',
    measurementId: 'G-5Y4MGM97GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAe6Fh73eEqzjJ1kvPmJO5514xgzeG9ts',
    appId: '1:525146998604:android:995abb13b1d20c3dde71e9',
    messagingSenderId: '525146998604',
    projectId: 'a-eye-397619',
    storageBucket: 'a-eye-397619.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY7bGOVupH52DSg2aVkF5LHEGIw_ume04',
    appId: '1:525146998604:ios:a1a761f2f9c36067de71e9',
    messagingSenderId: '525146998604',
    projectId: 'a-eye-397619',
    storageBucket: 'a-eye-397619.appspot.com',
    iosBundleId: 'com.example.alphaEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY7bGOVupH52DSg2aVkF5LHEGIw_ume04',
    appId: '1:525146998604:ios:a1a761f2f9c36067de71e9',
    messagingSenderId: '525146998604',
    projectId: 'a-eye-397619',
    storageBucket: 'a-eye-397619.appspot.com',
    iosBundleId: 'com.example.alphaEye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9S7RCLLDgcBx_9SWhQAY_wSjiMdhMMTc',
    appId: '1:525146998604:web:b1eba6c92146b6aade71e9',
    messagingSenderId: '525146998604',
    projectId: 'a-eye-397619',
    authDomain: 'a-eye-397619.firebaseapp.com',
    storageBucket: 'a-eye-397619.appspot.com',
    measurementId: 'G-WC3H5MWE1P',
  );
}
